### ISSUE TITLE
160725 일일회의 

### ISSUE THREAD

**Issue by flzl2008** [gnu-runtime/runtime#1]
1.  일일회의 결과는 앞으로 GitHub에 정리

2.  수요일까지 현재 today에 있는 task 전부 수행해오기

3. 월 수 금 모여서 몹프로그래밍 진행 및 일일회의, 화 목 온라인으로 일일회의만 

4. 서비스 기획 기능 추가 (협업툴 기능)

**Comment by probitanima11** [comment]
이슈는 작업할 단위를 나눠서 기록하고 관리하는 용도로 쓰는게 좋음
일일회의를 여기다 쓰면 그 목적이 애매해지므로 여기에 쓰는건 비추
깃헙에 쓰려면 옆옆에 Wiki에다 쓰는걸 추천
